### ISSUE TITLE
Exporting friend list

### ISSUE THREAD

**Issue by nurupo** [Tox/Tox-STS#12]
>Each client should include a way to manage friend lists, including the ability to export and import lists in a standard format (YET TO BE DECIDED). This will allow for users to switch clients and maintain backup copies. (Needs to be reworded)

There is no need in coming up with some format for exporting and importing friend lists, moreover making clients writing code for that. Toxcore has save/load functions that allow to get and set toxcore state bytes (which can be conveniently stored in a file, "tox data file"), which contain key pair, username, status message, **friend list** (with friend's name, status, status message, last seen, etc.), unconfirmed friend requests, etc. Tox data files were meant to be client-independent, so that you could move from one client to another without loosing your identity (keys) and friend list. They contain all client-independent information. So just ask clients to provide a way to export tox data bytes in a file and import them from it.

**Comment by zetok** [comment]
@nurupo looks like it's included in https://github.com/Tox/Tox-STS/blob/f4352353279455346753c5fd66f366c5e961b48f/STS.md#profile-management , and this issue is closable?
