### ISSUE TITLE
[Please read before posting] How to submit changes to the STS

### ISSUE THREAD

**Issue by stqism** [Tox/Tox-STS#47]
Please submit a formal Internet Draft with a title starting with [ID] + a title that sums up your proposed changes.

Info on writing an Internet Draft: http://www.rfc-editor.org/formatting.html

Upon evaluating your ID it will be added to a proposed markdown file with some basic pros/cons, a summary, and a link to your ID.

People are free to submit PRs with pros/cons regarding the proposal, but PRs to sts.md **WILL NOT BE MERGED**

We will then debate and decide on the proposal in a group setting composed of Tox developers and contributors, formally led by myself. Note that I will not be allowed to make any actions not decided upon in this group setting. We may decide to approve, reject, modify, or request clarification/changes to your proposal.

If you have write access to it as a member of the Tox org and you submit your changes and ideas forcefully without going through the formal review process you will be removed.

Please also be aware that any changes not made by myself will be removed. I will only make changes agreed upon. As well, this will be retroactively applied for issues up to a week before the authoring of this.

**Comment by zetok** [comment]
>Please submit a formal Internet Draft with a title starting with [ID] + a title that sums up your proposed changes.


No internet draft.

What should be included in both pull request and commit message, is what the change is about i.e. content of [proposals](https://github.com/Tox/Tox-STS/blob/master/proposals.md).
Make it easier for people who are going to evaluate change `;)`

====

>Upon evaluating your ID it will be added to a proposed markdown file with some basic pros/cons, a summary, and a link to your ID.


No ID. Pull request "ID" is sufficient to discuss it.

====

>People are free to submit PRs with pros/cons regarding the proposal, but PRs to sts.md WILL NOT BE MERGED


Provided that people will agree that given PR should be merged, it will be merged.

No one who has push access to this repo should change `sts.md` without going through pull request - the only exception to that is reverting changes made without going through pull request.

====

>We will then debate and decide on the proposal in a group setting composed of Tox developers and contributors, formally led by myself. Note that I will not be allowed to make any actions not decided upon in this group setting. We may decide to approve, reject, modify, or request clarification/changes to your proposal.


Now @stqism is not responsible for it.

Maintainers of major clients (Antidote, Antox, qTox, Toxy, µTox) can  cast a vote:
* `against`
* `supporting`
* `withheld their vote`

Majority vote (3/5) decides whether pull request should be merged.


====

>Please also be aware that any changes not made by myself will be removed. I will only make changes agreed upon. As well, this will be retroactively applied for issues up to a week before the authoring of this.


Anyone allowed to push to this repo can merge pull request that has been agreed to be merged.

**Comment by zetok** [comment]
@dvor @tux3 (other maintainers know already) ↑

**Comment by dvor** [comment]
Thanks for pointing out.

**Comment by ProMcTagonist** [comment]
Awesome.

**Comment by zetok** [comment]
Since there is pointer from README.md to file in which process of submitting changes is ~described, issue can be closed.
