### ISSUE TITLE
Avatars

### ISSUE THREAD

**Issue by krobelus** [Tox/Tox-STS#49]
As the avatar documentation was removed in irungentoo/toxcore@7001aa5dd04c50d1d74512c8cf7e662ce4b7d255 it would be nice if the parts that are still relevant could be added here.

**Comment by irungentoo** [comment]
https://github.com/irungentoo/Tox_Client_Guidelines/blob/master/Important/Avatars.md

**Comment by zetok** [comment]
@krobelus yep, now that there are easier steps for changing STS it should be "ported" here `;)`

**Comment by krobelus** [comment]
I think we should just update the link for now unless someone makes an effort to merge those repos.

**Comment by zetok** [comment]
Now in #52

**Comment by zetok** [comment]
Closing, since #52 got merged.
