### ISSUE TITLE
New home (STS is still being maintained) - https://github.com/zetok/Tox-STS

### ISSUE THREAD

**Issue by zetok** [Tox/Tox-STS#80]
```
[02:45:46] <subliun> Jfreegman: can you transfer the STS repo to zetok?
[02:46:24] <Jfreegman> subliun: he can fork it
[02:46:36] <subliun> then you lose issues and open PRs
[02:46:52] <Jfreegman> subliun: we don't want people to use the STS. it's archived for good
[02:47:21] <subliun> Jfreegman: but he's just going to fork it anyway..
[02:47:24] <Jfreegman> two standards will only confuse people
[02:47:35] <Jfreegman> he can do whatever he wants but we're not going to help
```

So, currently people who don't even really develop clients (spare for @JFreegman ) made a broken "replacement" for STS.

To force people to use it, they're killing STS.

Well, there are numerous other issues with the other thing - sad reality, you may get burned when you actually would try to use it / contribute.

Now, given that @subliun voiced his support for STS, I'm going to keep maintaining it in my fork - as always, it aims to provide best guidelines for clients, so nothing changes in that matter, and the only real change is repo URL: https://github.com/zetok/Tox-STS `;)`

As it always has been, my maintenance is about merging what client devs find good/wanted - so feel free to open new PRs in fork for things you would want to change / improve, so that they could be voted on `:)`

As for migrating PRs - I got a local copy of content of open PRs, and provided that they will pass voting here or in fork, they'll get merged, so no need to worry about that.

Also, I would like to get input from other maintainers of main clients who may be interested in using STS, namely, whether they're still interested in using it, and their thoughts on future of it:
@dvor, @tux3 @Impyy @GrayHatter ?

So long, and thanks for all the fish `;)`

**Comment by alexbakker** [comment]
Please exclude me from the voting process of the STS, I'm jumping ship to TCS.

**Comment by zetok** [comment]
@Impyy https://github.com/zetok/Tox-STS/commit/425985589aed1635360b379c26bea4def446675d `:|`

**Comment by dvor** [comment]
Having two different standards is bad and confusing. Why a new one was created?

**Comment by zetok** [comment]
> Why a new one was created?

The way I understand it, it was created to replace STS, since group of people who are managing `Tox` gh org didn't want to help with STS.

So yeah.

**Comment by JFreegman** [comment]
@dvor After two years of clients cherry picking from the STS or just flat out ignoring it, we realized that it was a failed experiment and that we should start fresh with a more coherent and minimalist approach. The TCS is basically just a list of minimum requirements for client compatibility and security, as opposed to trying to be a general development guideline.

As one of the few mobile client devs, we'd like to hear your input to make sure that it makes sense in the context of mobile clients. Please [check it out](https://tox.gitbooks.io/tox-client-standard/) and feel free to make issues or pull requests in [the repo](https://github.com/Tox/Tox-Client-Standard).

**Comment by dvor** [comment]
Will take a look, thanks.
